import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BlurGradientBackground from "@/components/BlurGradientBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-green-200 via-blue-200 to-purple-200">
        <BlurGradientBackground colors={["#ffffff","#aaf3b6","#a2c8f1","#f6efef","#f5f9d7","#cfcfce"]} />
        <Navbar />
        <main className="flex justify-center items-center min-h-full pt-16 pb-0">
          <div className="w-full max-w-max px-24 pb-10">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}